
version: '3.9'
services:
  postgres:
    container_name: kos_db
    image: postgres:12
    environment:
      POSTGRES_DB: claryfy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: docs@docs.com
      POSTGRES_PASSWORD: root
    ports:
      - "5050:80"